- name: Test s3
  hosts: local
  connection: local

  tasks:
    - name: Create new bucket
      aws_s3:
        bucket: testmeteam4
        mode: create
        region: ap-south-1
    - name: create ec2 instance
      action: 
        module: ec2 
        image: "ami-02a0ba3db0e4d42e3"
        instance_type: "t2.micro"
        state: present
        region: "ap-south-1"
        vpc_subnet_id: "subnet-0b4e618391f94d334"
        group: "terraform-20200409053430941900000001"
        key_name: "team4-demo-key-pair"
        instance_tags: 
          name: "Ansible-created"
