- name: Test s3
  hosts: local
  connection: local

  tasks:
      - name: Create new bucket
        aws_s3:
          bucket: testmeteam4
          mode: create
          region: ap-south-1
- name: Create Ec2 instances
  hosts: localhost
  gather_facts: false
  tasks:

  # Block is a Group of Tasks combined together
- name: Get Info Block
  block: 
    - name: Get Running instance Info

      ec2_instance_info:
      register: ec2info 

    - name: Print info
      debug: var="ec2info.instances"
             

    # By specifying always on the tag, 
    # I let this block to run all the time by module_default
    # this is for security to net create ec2 instances accidentally
    tags: ['always', 'getinfoonly']

- name: Create EC2 Block
  block: 

    - name: Launch ec2 instances
      tags: create_ec2
      ec2:
        region: us-east-1
        key_name: team4-demo-key-pair 
        group: sg-0d870542a674df816
        instance_type: t2.micro
        image: ami-02a0ba3db0e4d42e3
        wait: yes
        wait_timeout: 500
        count: 2
        instance_tags:
          name: appservers
          os: linux
        monitoring: no
        vpc_subnet_id: subnet-0b4e618391f94d334
        assign_public_ip: yes
      register: ec2
      delegate_to: localhost

    - name : Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      local_action:
        module: wait_for
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 120
      loop: "{{ ec2.instances }}"
  # By specifying never on the tag of this block, 
  # I let this block to run only when explicitely being called
  tags: ['never', 'ec2-create']
